const menu = document.getElementById('menu')
const hamburger = document.getElementById('hamburger')
const close = document.getElementById('close')
const search = document.getElementById('search')
const logo = document.getElementById('logo')

function showMenu() {
  menu.style.display = "inline-block"
  close.style.display = "block"
  hamburger.style.display = "none"
}

function hideMenu(){
  menu.style.display = "none"
  close.style.display = "none"
  hamburger.style.display = "flex"
}

hamburger.addEventListener("click", showMenu)
close.addEventListener("click", hideMenu)

// For cleaning out any script injection attacks

var regex = /(<([^>]+)>)/ig; // Maybe don't need this
var entityMap = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': '&quot;',
  "'": '&#39;',
  "/": '&#x2F;'
} 

function escapeHtml(string) {
  return String(string).replace(/[&<>"'\/]/g, function (s) {
    return entityMap[s];
})}

function getCityName(name){
var cities = {   
"aub":  " Auburn, Alabama ",
"bhm":  " Birmingham, Alabama ",
"dhn":  " Dothan, Alabama ",
"msl":  " Florence, Alabama ",
"anb":  " Gadsden-Anniston, Alabama ",
"hsv":  " Huntsville, Alabama ",
"mob":  " Mobile, Alabama ",
"mgm":  " Montgomery, Alabama ",
"tsc":  " Tuscaloosa, Alabama ",
"anc":  " Anchorage, Alaska ",
"fai":  " Fairbanks, Alaska ",
"ena":  " Kenai Peninsula, Alaska ",
"flg":  " Flagstaff, Arizona ",
"mhv":  " Mohave County, Arizona ",
"phx":  " Phoenix, Arizona ",
"prc":  " Prescott, Arizona ",
"tus":  " Tucson, Arizona ",
"yum":  " Yuma, Arizona ",
"fyv":  " Fayetteville, Arkansas ",
"jbr":  " Jonesboro, Arkansas ",
"lit":  " Little Rock, Arkansas ",
"txk":  " Texarkana, Arkansas ",
"bak":  " Bakersfield, California ",
"chc":  " Chico, California ",
"fre":  " Fresno, California ",
"hmb":  " Humboldt County, California ",
"imp":  " Imperial County, California ",
"inl":  " Inland Empire, California ",
"lax":  " Los Angeles, California ",
"mdo":  " Mendocino County, California ",
"mer":  " Merced, California ",
"mod":  " Modesto, California ",
"mtb":  " Monterey Bay, California ",
"orc":  " Orange County, California ",
"psp":  " Palm Springs, California ",
"rdd":  " Redding, California ",
"sac":  " Sacramento, California ",
"sdo":  " San Diego, California ",
"slo":  " San Luis Obispo, California ",
"sba":  " Santa Barbara, California ",
"smx":  " Santa Maria, California ",
"sfo":  " San Francisco Bay Area, California ",
"ssk":  " Siskiyou County, California ",
"stk":  " Stockton, California ",
"ssn":  " Susanville, California ",
"oxr":  " Ventura County, California ",
"vis":  " Visalia-Tulare, California ",
"ybs":  " Yuba-Sutter, California ",
"bou":  " Boulder, Colorado ",
"cos":  " Colorado Springs, Colorado ",
"den":  " Denver, Colorado ",
"ftc":  " Fort Collins, Colorado ",
"rck":  " High Rockies, Colorado ",
"pub":  " Pueblo, Colorado ",
"gjt":  " Western Slope, Colorado ",
"htf":  " Hartford, Connecticut ",
"hvn":  " New Haven, Connecticut ",
"dlw":  " Delaware",
"wdc":  " Washington D.C.",
"dab":  " Daytona Beach, Florida ",
"key":  " Florida Keys, Florida ",
"ftl":  " Fort Lauderdale, Florida ",
"fmy":  " Ft Myers, Florida ",
"gnv":  " Gainesville, Florida ",
"jax":  " Jacksonville, Florida ",
"lal":  " Lakeland, Florida ",
"mia":  " Miami, Florida ",
"oca":  " Ocala, Florida ",
"yps":  " Okaloosa, Florida ",
"orl":  " Orlando, Florida ",
"pfn":  " Panama City, Florida ",
"pns":  " Pensacola, Florida ",
"srq":  " Sarasota-Bradenton, Florida ",
"ust":  " St Augustine, Florida ",
"tal":  " Tallahassee, Florida ",
"tpa":  " Tampa Bay, Florida ",
"psl":  " Treasure Coast, Florida ",
"wpb":  " West Palm Beach, Florida ",
"aby":  " Albany, Georgia ",
"ahn":  " Athens, Georgia ",
"atl":  " Atlanta, Georgia ",
"aug":  " Augusta, Georgia ",
"bwk":  " Brunswick, Georgia ",
"csg":  " Columbus, Georgia ",
"mcn":  " Macon, Georgia ",
"sav":  " Savannah, Georgia ",
"tbr":  " Statesboro, Georgia ",
"vld":  " Valdosta, Georgia ",
"hnl":  " Hawaii ",
"boi":  " Boise, Idaho ",
"lws":  " Lewiston, Idaho ",
"twf":  " Twin Falls, Idaho ",
"bln":  " Bloomington, Illinois ",
"chm":  " Champaign Urbana, Illinois ",
"chi":  " Chicago, Illinois ",
"dil":  " Decatur, Illinois ",
"lsl":  " La Salle Co, Illinois ",
"mto":  " Mattoon-Charleston, Illinois ",
"pia":  " Peoria, Illinois ",
"rfd":  " Rockford, Illinois ",
"spi":  " Springfield, Illinois ",
"bmg":  " Bloomington, Indiana ",
"evw":  " Evansville, Indiana ",
"fwa":  " Fort Wayne, Indiana ",
"ind":  " Indianapolis, Indiana ",
"okk":  " Kokomo, Indiana ",
"laf":  " Lafayette, Indiana ",
"mun":  " Muncie, Indiana ",
"rin":  " Richmond, Indiana ",
"sbn":  " South Bend, Indiana ",
"tha":  " Terre Haute, Indiana ",
"ame":  " Ames, Iowa ",
"ced":  " Cedar Rapids, Iowa ",
"dsm":  " Des Moines, Iowa ",
"dbq":  " Dubuque, Iowa ",
"ftd":  " Fort Dodge, Iowa ",
"iac":  " Iowa City, Iowa ",
"msc":  " Mason City, Iowa ",
"mli":  " Quad Cities, Iowa ",
"sux":  " Sioux City, Iowa ",
"wlo":  " Waterloo, Iowa ",
"lwr":  " Lawrence, Kansas ",
"mhk":  " Manhattan, Kansas ",
"sns":  " Salina, Kansas ",
"tpk":  " Topeka, Kansas ",
"wic":  " Wichita, Kansas ",
"blg":  " Bowling Green, Kentucky ",
"lex":  " Lexington, Kentucky ",
"lou":  " Louisville, Kentucky ",
"owb":  " Owensboro, Kentucky ",
"btr":  " Baton Rouge, Louisiana ",
"hum":  " Houma, Louisiana ",
"lft":  " Lafayette, Louisiana ",
"lkc":  " Lake Charles, Louisiana ",
"mlu":  " Monroe, Louisiana ",
"nor":  " New Orleans, Louisiana ",
"shv":  " Shreveport, Louisiana ",
"mne":  " Bangor, Maine ",
"por":  " Portland, Maine ",
"anp":  " Annapolis, Maryland ",
"bal":  " Baltimore, Maryland ",
"fdk":  " Frederick, Maryland ",
"bos":  " Boston, Massachusetts ",
"cap":  " Cape Cod, Massachusetts ",
"sma":  " South Coast, Massachusetts ",
"wor":  " Worcester, Massachusetts ",
"aaa":  " Ann Arbor, Michigan ",
"btc":  " Battle Creek, Michigan ",
"det":  " Detroit, Michigan ",
"fnt":  " Flint, Michigan ",
"grr":  " Grand Rapids, Michigan ",
"hld":  " Holland, Michigan ",
"jxn":  " Jackson, Michigan ",
"kzo":  " Kalamazoo, Michigan ",
"lan":  " Lansing, Michigan ",
"mnr":  " Monroe, Michigan ",
"mkg":  " Muskegon, Michigan ",
"phn":  " Port Huron, Michigan ",
"mbs":  " Saginaw-Midland-Baycity, Michigan ",
"thb":  " The Thumb, Michigan ",
"yup":  " Upper Peninsula, Michigan ",
"bji":  " Bemidji, Minnesota ",
"brd":  " Brainerd, Minnesota ",
"dlh":  " Duluth, Minnesota ",
"mkt":  " Mankato, Minnesota ",
"min":  " Minneapolis / St Paul, Minnesota ",
"rmn":  " Rochester, Minnesota ",
"stc":  " St Cloud, Minnesota ",
"gpt":  " Gulfport, Mississippi ",
"usm":  " Hattiesburg, Mississippi ",
"jan":  " Jackson, Mississippi ",
"mei":  " Meridian, Mississippi ",
"cou":  " Columbia, Missouri ",
"jln":  " Joplin, Missouri ",
"ksc":  " Kansas City, Missouri ",
"krk":  " Kirksville, Missouri ",
"loz":  " Lake Of The Ozarks, Missouri ",
"sgf":  " Springfield, Missouri ",
"stj":  " St Joseph, Missouri ",
"stl":  " St Louis, Missouri ",
"bil":  " Billings, Montana ",
"bzn":  " Bozeman, Montana ",
"btm":  " Butte, Montana ",
"gtf":  " Great Falls, Montana ",
"hln":  " Helena, Montana ",
"fca":  " Kalispell, Montana ",
"mso":  " Missoula, Montana ",
"gil":  " Grand Island, Nebraska ",
"lnk":  " Lincoln, Nebraska ",
"lbf":  " North Platte, Nebraska ",
"oma":  " Omaha, Nebraska ",
"bff":  " Scottsbluff, Nebraska ",
"elk":  " Elko, Nevada ",
"lvg":  " Las Vegas, Nevada ",
"rno":  " Reno, Nevada ",
"nhm":  " New Hampshire",
"cnj":  " Central New Jersey ",
"jys":  " Jersey Shore, New Jersey ",
"njy":  " North New Jersey ",
"snj":  " South New Jersey ",
"abq":  " Albuquerque, New Mexico ",
"cvn":  " Clovis, New Mexico ",
"fnm":  " Farmington, New Mexico ",
"lcr":  " Las Cruces, New Mexico ",
"row":  " Roswell, New Mexico ",
"saf":  " Santa Fe, New Mexico ",
"alb":  " Albany, New York ",
"bgm":  " Binghamton, New York ",
"buf":  " Buffalo, New York ",
"cat":  " Catskills, New York ",
"chq":  " Chautauqua, New York ",
"elm":  " Elmira-Corning, New York ",
"fgl":  " Finger Lakes, New York ",
"gfl":  " Glens Falls, New York ",
"hud":  " Hudson Valley, New York ",
"ith":  " Ithaca, New York ",
"isp":  " Long Island, New York ",
"nyc":  " New York City, New York ",
"onh":  " Oneonta, New York ",
"plb":  " Plattsburgh-Adirondacks, New York ",
"ptd":  " Potsdam-Canton-Massena, New York ",
"rcs":  " Rochester, New York ",
"syr":  " Syracuse, New York ",
"tts":  " Twin Tiers, New York ",
"uti":  " Utica-Rome-Oneida, New York ",
"wtn":  " Watertown, New York ",
"ash":  " Asheville, North Carolina ",
"bnc":  " Boone, North Carolina ",
"cha":  " Charlotte, North Carolina ",
"fay":  " Fayetteville, North Carolina ",
"gbo":  " Greensboro, North Carolina ",
"hky":  " Hickory, North Carolina ",
"oaj":  " Jacksonville, North Carolina ",
"obx":  " Outer Banks, North Carolina ",
"ral":  " Raleigh / Durham , North Carolina ",
"wnc":  " Wilmington, North Carolina ",
"wsl":  " Winston-Salem, North Carolina ",
"bis":  " Bismarck, North Dakota ",
"far":  " Fargo, North Dakota ",
"gfk":  " Grand Forks, North Dakota ",
"cak":  " Akron, Ohio ",
"jfn":  " Ashtabula, Ohio ",
"ohu":  " Athens, Ohio ",
"chl":  " Chillicothe, Ohio ",
"cin":  " Cincinnati, Ohio ",
"cle":  " Cleveland, Ohio ",
"col":  " Columbus, Ohio ",
"day":  " Dayton, Ohio ",
"lma":  " Lima, Ohio ",
"mfd":  " Mansfield, Ohio ",
"sky":  " Sandusky, Ohio ",
"tol":  " Toledo, Ohio ",
"nph":  " Tuscarawas Co, Ohio ",
"yng":  " Youngstown, Ohio ",
"zyl":  " Zanesville, Ohio ",
"law":  " Lawton, Oklahoma ",
"okc":  " Oklahoma City, Oklahoma ",
"osu":  " Stillwater, Oklahoma ",
"tul":  " Tulsa, Oklahoma ",
"bnd":  " Bend, Oregon ",
"crv":  " Corvallis, Oregon ",
"eug":  " Eugene, Oregon ",
"klf":  " Klamath Falls, Oregon ",
"mfr":  " Medford-Ashland, Oregon ",
"cor":  " Oregon Coast, Oregon ",
"pdx":  " Portland, Oregon ",
"rbg":  " Roseburg, Oregon ",
"sle":  " Salem, Oregon ",
"aoo":  " Altoona-Johnstown, Pennsylvania ",
"cbg":  " Cumberland Valley, Pennsylvania ",
"eri":  " Erie, Pennsylvania ",
"hrs":  " Harrisburg, Pennsylvania ",
"lns":  " Lancaster, Pennsylvania ",
"alt":  " Lehigh Valley, Pennsylvania ",
"mdv":  " Meadville, Pennsylvania ",
"phi":  " Philadelphia, Pennsylvania ",
"pit":  " Pittsburgh, Pennsylvania ",
"poc":  " Poconos, Pennsylvania ",
"rea":  " Reading, Pennsylvania ",
"avp":  " Scranton/Wilkes-Barre, Pennsylvania ",
"psu":  " State College, Pennsylvania ",
"wpt":  " Williamsport, Pennsylvania ",
"yrk":  " York, Pennsylvania ",
"prv":  " Rhode Island",
"chs":  " Charleston, South Carolina ",
"cae":  " Columbia, South Carolina ",
"flo":  " Florence, South Carolina ",
"gsp":  " Greenville, South Carolina ",
"hhi":  " Hilton Head, South Carolina ",
"myr":  " Myrtle Beach, South Carolina ",
"csd":  " Pierre, South Dakota ",
"rap":  " Rapid City, South Dakota ",
"fsd":  " Sioux Falls, South Dakota ",
"cht":  " Chattanooga, Tennessee ",
"ckv":  " Clarksville, Tennessee ",
"coo":  " Cookeville, Tennessee ",
"jxt":  " Jackson , Tennessee ",
"knx":  " Knoxville, Tennessee ",
"mem":  " Memphis, Tennessee ",
"nsh":  " Nashville, Tennessee ",
"tri":  " Tri-Cities, Tennessee ",
"abi":  " Abilene, Texas ",
"ama":  " Amarillo, Texas ",
"aus":  " Austin, Texas ",
"bpt":  " Beaumont / Port Arthur, Texas ",
"bro":  " Brownsville, Texas ",
"cst":  " College Station, Texas ",
"crp":  " Corpus Christi, Texas ",
"dal":  " Dallas / Fort Worth, Texas ",
"drt":  " Del Rio, Texas ",
"elp":  " El Paso, Texas ",
"gls":  " Galveston, Texas ",
"hou":  " Houston, Texas ",
"grk":  " Killeen, Texas ",
"lrd":  " Laredo, Texas ",
"lbb":  " Lubbock, Texas ",
"mca":  " Mcallen, Texas ",
"odm":  " Odessa / Midland, Texas ",
"sjt":  " San Angelo, Texas ",
"sat":  " San Antonio, Texas ",
"tsu":  " San Marcos, Texas ",
"txm":  " Texoma, Texas ",
"etx":  " Tyler, Texas ",
"vtx":  " Victoria, Texas ",
"wco":  " Waco, Texas ",
"wtf":  " Wichita Falls, Texas ",
"lgu":  " Logan, Utah ",
"ogd":  " Ogden-Clearfield, Utah ",
"pvu":  " Provo, Utah ",
"slc":  " Salt Lake City, Utah ",
"stg":  " St George, Utah ",
"brl":  " Burlington, Vermont ",
"mon":  " Montpelier, Vermont ",
"brb":  " Brattleboro, Vermont ",
"uva":  " Charlottesville, Virginia ",
"dnv":  " Danville, Virginia ",
"ezf":  " Fredericksburg, Virginia ",
"nfk":  " Hampton Roads, Virginia ",
"shd":  " Harrisonburg, Virginia ",
"lyn":  " Lynchburg, Virginia ",
"vpi":  " New River Valley, Virginia ",
"ric":  " Richmond, Virginia ",
"roa":  " Roanoke, Virginia ",
"okv":  " Winchester, Virginia ",
"bli":  " Bellingham, Washington ",
"kpr":  " Kennewick-Pasco-Richland, Washington ",
"mlk":  " Moses Lake, Washington ",
"olp":  " Olympic Peninsula, Washington ",
"plm":  " Pullman, Washington ",
"sea":  " Seattle-Tacoma, Washington ",
"mvw":  " Skagit, Washington ",
"spk":  " Spokane, Washington ",
"wen":  " Wenatchee, Washington ",
"yak":  " Yakima, Washington ",
"crw":  " Charleston, West Virginia ",
"hts":  " Huntington, West Virginia ",
"wvu":  " Morgantown, West Virginia ",
"pkb":  " Parkersburg, West Virginia ",
"wva":  " Wheeling, West Virginia ",
"app":  " Appleton, Wisconsin ",
"eau":  " Eau Claire, Wisconsin ",
"grb":  " Green Bay, Wisconsin ",
"jvl":  " Janesville, Wisconsin ",
"rac":  " Kenosha-Racine, Wisconsin ",
"lse":  " La Crosse, Wisconsin ",
"mad":  " Madison, Wisconsin ",
"mil":  " Milwaukee, Wisconsin ",
"sbm":  " Sheboygan, Wisconsin ",
"wau":  " Wausau, Wisconsin ",
"wyo":  " Cheyenne, Wyoming"
}
var city = (cities[name])
return city
}

// Search //
const input = document.getElementById('search')
const input1 = document.getElementById('search1')

input.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    const query = document.getElementById('search').value
    event.preventDefault()
    window.location.href = './search.html?query=' + query
}})

input1.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    const query = document.getElementById('search1').value
    event.preventDefault()
    window.location.href = './search.html?query=' + query
}})
    
